### ISSUE TITLE
googleapi: Error 403: APK has the wrong package name., forbidden

### ISSUE THREAD

**Issue by AlexandreRoba** [bitrise-steplib/steps-google-play-deploy#113] opened 2021-02-16 10:35 UTC
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 3.2.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description
I'm getting the following error :
```
+------------------------------------------------------------------------------+

| (10) google-play-deploy@3                                                    |
+------------------------------------------------------------------------------+
| id: google-play-deploy                                                       |
| version: 3.2.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-02-16T09:32:37Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Getting configuration
Configs:
- JSONKeyPath: *****
- PackageName: YY.XXXXXXXXXXX.ZZZ
- AppPath: /Users/vagrant/deploy/app-release.apk\n
- ExpansionfilePath: 
- Track: internal
- UserFraction: 0
- UpdatePriority: 0
- WhatsnewsDir: 
- MappingFile: 
- ReleaseName: 
Found .apk file: /Users/vagrant/deploy/app-release.apk
Configuration read successfully
Authenticating
Authenticated client created
Create new edit
 editID: 03319851535039046096
Edit insert created
Upload apks or app bundles
Found .apk file: /Users/vagrant/deploy/app-release.apk
Uploading /Users/vagrant/deploy/app-release.apk 1/1
Failed to upload APKs: failed to upload apk, error: googleapi: Error 403: APK has the wrong package name., forbidden
```

The error message does not make much sens. Previsouly I started by having a 404 Error when I was having indeed the wrong package name (But the wrong package name was showing on the error message. But Since I have recreated a new app(You cannot change the bundle id once the app has been uploaded the first time :() and uploaded the first package with the exact same bundle id as the one defined on the build. I can see on the play store the package name of the app which is exactly "YY.XXXXXXXXXXX.ZZZ" (Replaced by dummy name)

I try to follow the steps recommanded on this link: https://blog.bitrise.io/how-to-deploy-android-app-to-google-play-store
[X] Created Service Account and provided Admin right on the APP
[X] Manually uploaded a first version of the package to the play store (With the same package name) to internal testing
[X] Configured the json service account on bitrise with Admin right on all apps of the google play account. Downloaded the JSON and uploaded it to Bitrise.

I have repeated those steps on the new app on the play store with the right package name.

### Bitrise info

- Build URL:  https://app.bitrise.io/build/90e5ee8135651a03#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

### Steps to reproduce

simply run the build with workflow PRD_ANDROID on branch master

**Comment by ofalvai** [comment] 2021-02-26 13:56
Are you sure the service account's private key file that is uploaded to Bitrise is correct? Maybe Bitrise still has credentials to your first app, and it's trying to upload the artifact to the wrong Play Store app.

**Comment by AlexandreRoba** [comment] 2021-02-27 07:46
The key file is valid as far as I can tell cause I haven't change it and it still works for the first app. Do I have to regenerate a new key If I change the service account access? This would be weird and illogical. The only operation I have done on the service account is adding it full access to the new google play app project. I have then reused the same json key that was already on bit rise for the first project. Nevertheless I will create a new key and try with this one to make sure this is not the problem.

**Comment by AlexandreRoba** [comment] 2021-02-27 10:36
@ofalvai thanks for the feedback. i confirm. i have generated a new key and uploaded the JSON and still getting the same error. I confirm the Service Account is provided full management rights on the Google play project. This is insane :(

**Comment by ofalvai** [comment] 2021-03-03 11:37
@AlexandreRoba the next thing I would check is the package name of the final APK, just to be 100% sure it has the same package name as what you have configured in the Play Deploy step.

If you include a [Deploy to Bitrise.io](https://www.bitrise.io/integrations/steps/deploy-to-bitrise-io) step in the workflow, then you can download the APK from the Apps & Artifacts tab on the build page, then verify its package name using Android Studio or similar tools.

**Comment by tokou** [comment] 2021-04-15 15:02
I started having the same issue after updating from 3.0.2 to 3.3.0
I tried reverting to 3.0.2 and deleting cache but it still happens.

**Comment by mateherber** [comment] 2021-08-10 12:05
Hi @AlexandreRoba, @tokou, 

Do you still experience this issue? I can't reproduce it in our environment and would be happy to track this case if you still are able to reproduce it.

**Comment by mateherber** [comment] 2021-08-30 09:26
I'm going to close this issue now. If you experience a similar issue in the future, please make sure to open a new issue for us with the details.

**Closed by mateherber** 2021-08-30 09:26 UTC
